name: Healthy Punch Card

on:
  workflow_dispatch:

  schedule:
  - cron: '10 16 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Python
        run: |
          sudo apt update && \
          sudo apt install python3
        
      - name: requirements
        run: |
          pip3 install -r requirements.txt

      - name: Punch Card
        env:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
        run: |
          python3 auto.py --username=$username --password=$password
